### ISSUE TITLE
Issue with implementing via Jenkins DSL (not signature of method)

### ISSUE THREAD

**Issue by ShadowScorpion** [jenkinsci/generic-webhook-trigger-plugin#151]
Have a problem with the installation of GenericWebHookTrigger plugin via Jenkins DSL
We are using Jenkins ver. 2.138 and tried old and latest versions of the plugin, but still, all the time have the same exception

> Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.GenericTrigger() is applicable for argument types: (script$_run_closure2$_closure5$_closure11) values: [script$_run_closure2$_closure5$_closure11@673be18f]

In dependencies added all plugins included all own plugin, and still same error.

Kindly ask to help to understand what is wrong, cause plugin is working well on Jenkins, but implement from DSL is not possible.

P.S. Tried to import java files, but it's taking dependencies in infinity loop.

Thanks

**Comment by tomasbjerre** [comment]
Can you supply the DSL that does not work?

**Comment by ShadowScorpion** [comment]
Thank you for the quick answer! 
Unfortunately it's not depends on code in my case.
Trying to launch the standart example which was provided : 
```
job('Generic Job Example') {
 parameters {
  stringParam('VARIABLE_FROM_POST', '')
  stringParam('VARIABLE_FROM_REQUEST', '')
 }
 
 triggers {
  genericTrigger {
   genericVariables {
    genericVariable {
     key("VARIABLE_FROM_POST")
     value("\$.something")
     expressionType("JSONPath")
     regexpFilter("")
    }
   }
   genericRequestVariables {
    genericRequestVariable {
     key("VARIABLE_FROM_REQUEST")
     regexpFilter("")
    }
   }
   regexpFilterText("\$VARIABLE_FROM_POST")
   regexpFilterExpression("aRegExp")
  }
 }
 
 steps {
  shell('''
echo $VARIABLE_FROM_POST
echo $VARIABLE_FROM_REQUEST
  ''')
 }
}
```
But still same error : 

> :compileJava NO-SOURCE
> :compileGroovy UP-TO-DATE
> :processResources UP-TO-DATE
> :classes UP-TO-DATE
> :rest
> 
> processing file: /tmp/jenkins-job-dsl/jobs/test.groovy
> Processing provided DSL script
> Exception in thread "main" javaposse.jobdsl.dsl.DslScriptException: (script, line 8) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.genericTrigger() is applicable for argument types: (script$_run_closure1$_closure3$_closure5) values: [script$_run_closure1$_closure3$_closure5@413f69cc]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
>         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:107)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader$_runScripts_closure1.doCall(AbstractDslScriptLoader.groovy:60)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at groovy.lang.Closure.call(Closure.java:430)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
>         at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader$runScripts$0.callCurrent(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:81)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader$runScript.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>         at com.dslexample.rest.RestApiScriptRunner$_run_closure1.doCall(RestApiScriptRunner.groovy:25)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at groovy.lang.Closure.call(Closure.java:430)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
>         at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>         at com.dslexample.rest.RestApiScriptRunner.run(RestApiScriptRunner.groovy:22)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
>         at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
>         at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:410)
>         at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
>         at com.dslexample.rest.RestApiScriptRunner.main(RestApiScriptRunner.groovy)
> Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.genericTrigger() is applicable for argument types: (script$_run_closure1$_closure3$_closure5) values: [script$_run_closure1$_closure3$_closure5@413f69cc]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
>         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
>         at javaposse.jobdsl.dsl.AbstractExtensibleContext.methodMissing(AbstractExtensibleContext.groovy:19)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)
>         at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
>         at javaposse.jobdsl.dsl.AbstractContext.invokeMethod(AbstractContext.groovy)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:430)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:371)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
>         at script$_run_closure1$_closure3.doCall(script:8)
>         at script$_run_closure1$_closure3.doCall(script)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
>         at javaposse.jobdsl.dsl.ContextHelper.executeInContext(ContextHelper.groovy:16)
>         at javaposse.jobdsl.dsl.ContextHelper$executeInContext.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
>         at javaposse.jobdsl.dsl.Job.triggers(Job.groovy:568)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
>         at script$_run_closure1.doCall(script:7)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at groovy.lang.Closure.call(Closure.java:430)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:242)
>         at org.codehaus.groovy.runtime.dgm$757.invoke(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>         at javaposse.jobdsl.dsl.JobParent.processItem(JobParent.groovy:116)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
>         at javaposse.jobdsl.dsl.JobParent.freeStyleJob(JobParent.groovy:49)
>         at javaposse.jobdsl.dsl.JobParent$freeStyleJob$0.callCurrent(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
>         at javaposse.jobdsl.dsl.JobParent.job(JobParent.groovy:41)
>         at javaposse.jobdsl.dsl.DslFactory$job.callCurrent(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
>         at script.run(script:1)
>         at script$run.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:124)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
>         at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:101)
>         ... 79 more
> :rest FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':rest'.
> > Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1.673 secs

**Comment by tomasbjerre** [comment]
Are you trying to use job dsl from Gradle? You should install the job dsl
plugin in jenkins and use it to execute the dsl.

Den ons 11 dec. 2019 08:58Kostiantyn Skrypnyk <notifications@github.com>
skrev:

**Comment by ShadowScorpion** [comment]
It's installed and using it for other jobs without this plugin.
But unfortunately, I have missed something in this case.

I believe need something should be imported in Gradlew
Can you please assist what I should do on Gradlew side?
Thanks

**Comment by ShadowScorpion** [comment]
Need to execute this DSL on plugin "Job DSL" version 1.71
But also tried on latest one 1.76 and same error :(

**Comment by tomasbjerre** [comment]
I dont see what gradle has to do with job dsl?

Den ons 11 dec. 2019 12:51Kostiantyn Skrypnyk <notifications@github.com>
skrev:

**Comment by ShadowScorpion** [comment]
Implement the job to Jenkins

Full command attached with info trace


[stacktrace.txt](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/3950250/stacktrace.txt)

**Comment by tomasbjerre** [comment]
I still dont understand what you are trying to do. Can you repeat this in an open repository?

**Comment by ShadowScorpion** [comment]
The problem is in Jenkins, case no class of GenericTrigger from DSL
I have fixed this issue via this :
`job('ci_test') {
    configure {
      it / triggers << 'org.jenkinsci.plugins.gwt.GenericTrigger' {
        spec()
        genericVariables {
          'org.jenkinsci.plugins.gwt.GenericVariable' {
            expressionType("JSONPath")
            key("heal")
            value("\$.test")
            regexpFilter("something")
            defaultValue("something")
          }
        }
        regexpFilterText()
        regexpFilterExpression()
        printPostContent("true")
        printContributedVariables("true")
        causeString("Generic Cause")
        token("monitSelfHeal")
        silentResponse("true")
      }
    }
}`
But still need to rewrite on native DSL module
Have you any ideas why it can be? maybe include something on dependencies?

**Comment by tomasbjerre** [comment]
The DSL in the readme works for me. Still dont understand what gradle has to do with this.

**Comment by SGastons** [comment]
Hello!
I have this problem too! We are using gradle to programmatically create/update jobs in jenkins and the problem can be fixed by importing this plugin in the build.gradle file. 
You need to add the plugin under dependencies.

> dependencies {
    compile("com.here.gradle.plugins:gradle-jenkins-jobdsl-plugin:${jenkinsJobdslPluginVersion}") {
        exclude(module: 'org-netbeans-insane')
        exclude(module: 'xalan')
        exclude(module: 'xercesImpl')
    }
    jenkinsPlugins 'org.jenkins-ci.plugins:cloudbees-folder:6.2.1'
    jenkinsPlugins 'org.jenkins-ci.plugins:timestamper:1.8.9'
    [HERE] jenkinsPlugins 'org.jenkins-ci.plugins:generic-webhook-trigger:1.66'
}
