### ISSUE TITLE
Error 500 when receiving a request of type `multipart/form-data`

### ISSUE THREAD

**Issue by jficz** [jenkinsci/generic-webhook-trigger-plugin#350]
### Jenkins and plugins versions report

Jenkins returns error 500 and a full generic Jenkins UI HTML page with `A problem occurred while processing the request` when doing a request containing form data:

```
curl -X POST -H "Content-Type: multipart/form-data; boundary=--xxxboundary" -d @body 'http://jenkins/generic-webhook-trigger/invoke?token=<token>'
```

`body` contains a json file:
```
--xxxboundary
Content-Disposition: form-data; name="event"; filename="data.json"
Content-Type: application/json

{"data": "some data"}
--xxxboundary
```

pipeline:
```
pipeline {
  agent any
  stages {
    stage('printenv') {
      steps {
        sh """#!/usr/bin/env bash
          env
        """
      }
    }
  }
}
```

Job has no parameters though setting parameters doesn't seem to make a difference.

Job doesn't trigger so no build logs, etc.

Jenkins logs: https://gist.github.com/jficz/51b28f9bbae73fc847a6d496bef5889f

This is a minimal reproducible example I could figure out. In reality the webhook is triggered by [matrix-hookshot](https://github.com/matrix-org/matrix-hookshot) and contains a few more headers and a different user agent. The body is, however, the same (except different valid json and boundaries of course).

Expected result is at least parseable response stating a reasonable error message or ideally a job trigger with the form data injected.

Jenkins info (gwh version moved to the top):
```
Jenkins: 2.492.1
OS: Linux - 6.9.12-2
Java: 17.0.13 - Oracle Corporation (OpenJDK 64-Bit Server VM)
---
generic-webhook-trigger:2.3.1

antisamy-markup-formatter:173.v680e3a_b_69ff3
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
asm-api:9.7.1-97.v4cc844130d97
bootstrap5-api:5.3.3-2
bouncycastle-api:2.30.1.80-256.vf98926042a_9b_
branch-api:2.1214.v3f652804588d
build-name-setter:2.5.0
build-timeout:1.36
build-user-vars-plugin:195.v8c35f9d5c3dc
build-with-parameters:76.v9382db_f78962
caffeine-api:3.2.0-161.v691ef352cee1
checks-api:367.v18b_7f530e54a_
cloudbees-folder:6.982.vf165a_16c9507
command-launcher:118.v72741845c17a_
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.13.0-153.v91dcd89e2a_22
conditional-buildstep:1.5.0
copyartifact:765.v0357cc6e6eb_3
credentials:1408.va_622a_b_f5b_1b_1
credentials-binding:687.v619cb_15e923f
dark-theme:524.vd675b_22b_30cb_
dashboard-view:2.528.v3470c02b_d7c9
display-url-api:2.209.v582ed814ff2f
durable-task:587.v84b_877235b_45
echarts-api:5.6.0-2
eddsa-api:0.3.0-13.v7cb_69ed68f00
email-ext:1876.v28d8d38315b_d
emailext-template:224.va_f6a_ecd5d46e
embeddable-build-status:548.v5653c6e28c41
envinject-api:1.235.va_14c74f8f487
extended-security-settings:1.3
file-parameters:358.v9ed4456a_169a_
font-awesome-api:6.7.2-1
fstrigger:1.02
git:5.7.0
git-client:6.1.2
git-parameter:0.11.0
gson-api:2.12.1-113.v347686d6729f
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:82.v0597178874e1
jackson2-api:2.17.0-389.va_5c7e45cd806
jakarta-activation-api:2.1.3-2
jakarta-mail-api:2.1.3-2
javax-activation-api:1.2.0-8
javax-mail-api:1.6.2-11
jaxb:2.3.9-133.vb_ec76a_73f706
jdk-tool:83.v417146707a_3d
joda-time-api:2.13.1-115.va_6b_5f8efb_1d8
jquery3-api:3.7.1-3
json-api:20250107-125.v28b_a_ffa_eb_f01
json-path-api:2.9.0-148.v22a_7ffe323ce
junit:1317.v5b_35d792b_06a_
mailer:489.vd4b_25144138f
manage-permission:1.0.1
mask-passwords:188.v66e477dcb_24a_
matrix-project:845.vffd7fa_f27555
metrics:4.2.21-464.vc9fa_a_0d6265d
mina-sshd-api-common:2.14.0-143.v2b_362fc39576
mina-sshd-api-core:2.14.0-143.v2b_362fc39576
outbound-webhook:0.3.0
parameterized-trigger:840.v3c7d4a_a_5e6c7
pipeline-build-step:557.v95d96f77b_2b_8
pipeline-graph-analysis:231.v56354571a_da_0
pipeline-graph-view:419.v946ff4a_49e1c
pipeline-groovy-lib:752.vdddedf804e72
pipeline-input-step:515.v8857b_eb_b_910c
pipeline-milestone-step:127.vb_52887ca_3b_6d
pipeline-model-api:2.2236.va_b_88ceec798f
pipeline-model-definition:2.2236.va_b_88ceec798f
pipeline-model-extensions:2.2236.va_b_88ceec798f
pipeline-rest-api:2.37
pipeline-stage-step:322.vecffa_99f371c
pipeline-stage-tags-metadata:2.2236.va_b_88ceec798f
pipeline-stage-view:2.37
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:6.0.0
poll-mailbox-trigger-plugin:1.026
rebuild:338.va_0a_b_50e29397
resource-disposer:0.25
role-strategy:756.v978cb_392eb_d3
run-condition:243.v3c3f94e46a_8b_
run-condition-extras:0.3
scm-api:704.v3ce5c542825a_
script-security:1373.vb_b_4a_a_c26fa_00
snakeyaml-api:2.3-123.v13484c65210a_
ssh-credentials:355.v9b_e5b_cde5003
sshd:3.353.v2b_d33c46e970
structs:343.vdcf37b_a_c81d5
theme-manager:278.v2e3c063e42cc
timestamper:1.28
token-macro:444.v52de7e9c573d
trilead-api:2.192.vc50a_d147e369
variant:70.va_d9f17f859e0
webhook-step:342.v620877effe14
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1363.v03f731255494
workflow-basic-steps:1079.vce64b_a_929c5a_
workflow-cps:4032.vf3248d9c3fee
workflow-durable-task-step:1405.v1fcd4a_d00096
workflow-job:1505.vea_4b_20a_4a_495
workflow-multibranch:803.v08103b_87c280
workflow-scm-step:437.v05a_f66b_e5ef8
workflow-step-api:700.v6e45cb_a_5a_a_21
workflow-support:961.v51869f7b_d409
ws-cleanup:0.48
xtrigger-api:1.2
```

**Comment by jglick** [comment]
Possibly fixed in Jenkins 2.499.

**Comment by tomasbjerre** [comment]
@jficz is this issue resolved with 2.499?

**Comment by jficz** [comment]
Don't know yet, only had a chance to test on 1.492.2 and it's still broken there. Can't tell if the patch made it to that release. I'll try to test on 1.500

**Comment by jglick** [comment]
Either way, the issue could be worked around in this plugin in prior Jenkins release by just choosing a different idiom for https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/8f2edb6a150f807b47d7dd802dac71e701c4d54f/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L74 and https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/8f2edb6a150f807b47d7dd802dac71e701c4d54f/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L102 (and writing a `JenkinsRule` test covering this functionality, which I guess would reliably fail with a `jenkins.version` older than 2.499 without changes to `GenericWebHookRequestReceiver`).

**Comment by jficz** [comment]
I can confirm 2.500 doesn't give 500 anymore.

But it still doesn't work as I'd expect. I'll check the issues and open a new one if this hasn't been reported yet.

Not sure if my report is enough for you to close the ticket or not but for me the issue is fixed (though I'd be happy to see it land in LTS).

**Comment by jglick** [comment]
> I'd be happy to see it land in LTS

Not too late for 2.492.3 I guess, but as in https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/350#issuecomment-2710757893 it would likely be simpler to just avoid the formerly broken method in this plugin.

**Comment by tomasbjerre** [comment]
What method are you suggesting it should be replaced with? "choosing a different idiom" does not say much.

**Comment by jglick** [comment]
Sorry, not sure offhand, but there are a bunch of `HttpServletRequest` methods to choose from.

**Comment by tomasbjerre** [comment]
Closing this because it is a bug in Jenkins, not this plugin.
