### ISSUE TITLE
Credentials Parameter converted to String rather than Credentials

### ISSUE THREAD

**Issue by rcao5** [jenkinsci/generic-webhook-trigger-plugin#61]
I am using version 1.37, and I when I specify a credential parameter using "This project is parameterized", the credential seems to be converted to a string when the job is triggered. It looks like a similar issue happened before with booleans: https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/58, and that was fixed; could you take a look to see if you can implement a similar fix for credentials parameters?

Thanks

**Comment by rcao5** [comment]
For some more information, it seems that the credentials parameters is from this plugin: https://plugins.jenkins.io/credentials-binding

**Comment by tomasbjerre** [comment]
Should be fixed now in 1.38.

**Comment by rcao5** [comment]
I'm still getting the same error:

```
org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: ${BS_ACCESS}
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler.forId(CredentialsBindingHandler.java:107)
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler$forId.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
```

It looks like the Credentials Parameter is kept as the correct type, but is not being exported to a environment variable correctly. Can you please take a look at this again? Thanks!

**Comment by tomasbjerre** [comment]
How did you configure the plugin?

**Comment by rcao5** [comment]
Thanks for your quick reply; I have a Credentials Parameter as follows:

![credentials_jenkins](https://user-images.githubusercontent.com/15202629/41866909-6654dbc8-7866-11e8-9b0a-c81bb0e58c63.JPG)

And in my build triggers, I've configured Generic Webhook Trigger to build only when a commit is pushed to the master branch:

![gwt_jenkins](https://user-images.githubusercontent.com/15202629/41866946-86a0b690-7866-11e8-821c-34bbc205ec07.JPG)

And in my pipeline script, I want to use the credential parameter by calling `credentials('${BS_ACCESS}')`, which works fine when I trigger the job manually, but when the job through the github webhook, I'm getting the CredentialNotFoundException I commented above.

**Comment by tomasbjerre** [comment]
What if you use `credentials("${BS_ACCESS}")` ?

**Comment by rcao5** [comment]
Hmm, that is odd, using the double quotes fixed the issue, thanks so much! :)
